version: "3.4"

services:
  website:
    build:
      context: ./
      dockerfile: docker/dev.Dockerfile
    container_name: website
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
