version: "3.4"

services:
  website:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: website
    env_file: .env
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules/
