export const regions = [
  { code: 13, name: 'Abruzzo', slug: 'abruzzo' },
  { code: 17, name: 'Basilicata', slug: 'basilicata' },
  { code: 18, name: 'Calabria', slug: 'calabria' },
  { code: 15, name: 'Campania', slug: 'campania' },
  { code: 8, name: 'Emilia-Romagna', slug: 'emiliaromagna' },
  { code: 6, name: 'Friuli Venezia Giulia', slug: 'friuliveneziagiulia' },
  { code: 12, name: 'Lazio', slug: 'lazio' },
  { code: 7, name: 'Liguria', slug: 'liguria' },
  { code: 3, name: 'Lombardia', slug: 'lombardia' },
  { code: 11, name: 'Marche', slug: 'marche' },
  { code: 14, name: 'Molise', slug: 'molise' },
  { code: 21, name: 'P.A. Bolzano', slug: 'bolzano' },
  { code: 22, name: 'P.A. Trento', slug: 'trento' },
  { code: 1, name: 'Piemonte', slug: 'piemonte' },
  { code: 16, name: 'Puglia', slug: 'puglia' },
  { code: 20, name: 'Sardegna', slug: 'sardegna' },
  { code: 19, name: 'Sicilia', slug: 'sicilia' },
  { code: 9, name: 'Toscana', slug: 'toscana' },
  { code: 10, name: 'Umbria', slug: 'umbria' },
  { code: 2, name: "Valle d'Aosta", slug: 'valledaosta' },
  { code: 5, name: 'Veneto', slug: 'veneto' }
]
