name: CI

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: ssh-keyscan "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Update website
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: ssh root@"$SSH_HOST" ./updateWebsite.sh
