export enum Regions {
  abruzzo = 'abruzzo',
  basilicata = 'basilicata',
  bolzano = 'bolzano',
  calabria = 'calabria',
  campania = 'campania',
  emiliaromagna = 'emiliaromagna',
  friuliveneziagiulia = 'friuliveneziagiulia',
  lazio = 'lazio',
  liguria = 'liguria',
  lombardia = 'lombardia',
  marche = 'marche',
  molise = 'molise',
  piemonte = 'piemonte',
  puglia = 'puglia',
  sardegna = 'sardegna',
  sicilia = 'sicilia',
  toscana = 'toscana',
  trento = 'trento',
  umbria = 'umbria',
  valledaosta = 'valledaosta',
  veneto = 'veneto'
}
